apiVersion: 1

datasources:
  - name: Fleet Loki
    uid: fleet-loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    basicAuth: true
    basicAuthUser: ${LOKI_USER}
    secureJsonData:
      basicAuthPassword: ${LOKI_TOKEN}
    jsonData:
      maxLines: 1000
      timeout: 60
    editable: false
