# Health monitoring config — generated by edge-apply
# Operator can edit. Agent reads but does not write.

monitored_files:
  - path: "{{ WORK_DIR }}/blog/entries"
    glob: "*.md"
    category: blog
    threshold_days: 3
    remedy_skill: "/{{ SKILL_PREFIX }}-planner"

  - path: "{{ WORK_DIR }}/threads"
    glob: "*.md"
    category: threads
    threshold_days: 7
    remedy_skill: "/{{ SKILL_PREFIX }}-planner"

  - path: "{{ WORK_DIR }}/reports"
    glob: "*.html"
    category: reports
    threshold_days: 5
    remedy_skill: "/{{ SKILL_PREFIX }}-report"
