#!/usr/bin/env bash
# paths.sh — Shared path resolution for shell scripts.
# Source this from any script: source "$(dirname "$0")/../config/paths.sh"

set -u

_PATHS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_PATHS_REPO_DEFAULT="$(cd "${_PATHS_SCRIPT_DIR}/.." && pwd)"

# --- Shared genotype root (repo checkout) ---
EDGE_REPO_DIR="${EDGE_REPO_DIR:-${EDGE_DIR:-${_PATHS_REPO_DEFAULT}}}"
EDGE_DIR="$EDGE_REPO_DIR"   # Runtime-root alias used by older tools.

# --- Load branding.yaml from genotype root ---
BRANDING_FILE="$EDGE_REPO_DIR/config/branding.yaml"

branding_value() {
  local pattern="$1"
  local file="$2"
  grep "$pattern" "$file" 2>/dev/null | head -1 | awk '{print $2}' | tr -d '"' || true
}

if [ -f "$BRANDING_FILE" ]; then
  BLOG_PORT=$(branding_value '^  port:' "$BRANDING_FILE")
  BLOG_AUTH_ENABLED=$(branding_value '^  auth_enabled:' "$BRANDING_FILE")
  BLOG_AUTH_USER=$(branding_value '^  auth_user:' "$BRANDING_FILE")
  BLOG_AUTH_PASS=$(branding_value '^  auth_pass:' "$BRANDING_FILE")
  MEMORY_PROJECT_DIR="${MEMORY_PROJECT_DIR:-$(branding_value '^memory_project_dir:' "$BRANDING_FILE")}"
  SKILL_PREFIX=$(branding_value '^skill_prefix:' "$BRANDING_FILE")
  EDGE_INSTANCE_FROM_BRANDING=$(branding_value '^codename:' "$BRANDING_FILE")
  EDGE_STATE_DIR_FROM_BRANDING=$(branding_value '^edge_state_dir:' "$BRANDING_FILE")
else
  BLOG_PORT=8766
  BLOG_AUTH_ENABLED=false
  BLOG_AUTH_USER=""
  BLOG_AUTH_PASS=""
  MEMORY_PROJECT_DIR=""
  SKILL_PREFIX="agent"
  EDGE_INSTANCE_FROM_BRANDING=""
  EDGE_STATE_DIR_FROM_BRANDING=""
fi

EDGE_INSTANCE="${EDGE_INSTANCE:-${EDGE_CODENAME:-${EDGE_INSTANCE_FROM_BRANDING:-${SKILL_PREFIX:-agent}}}}"
EDGE_STATE_DIR="${EDGE_STATE_DIR:-${EDGE_STATE_DIR_FROM_BRANDING:-${EDGE_REPO_DIR}}}"
EDGE_HOME="$EDGE_STATE_DIR"  # Mutable-root alias used by older tools.

# Defaults
BLOG_PORT=${BLOG_PORT:-8766}
SKILL_PREFIX=${SKILL_PREFIX:-agent}
BLOG_URL="http://localhost:${BLOG_PORT}"

# Curl auth flag
CURL_AUTH=""
if [ "$BLOG_AUTH_ENABLED" = "true" ] && [ -n "$BLOG_AUTH_USER" ]; then
  CURL_AUTH="-u ${BLOG_AUTH_USER}:${BLOG_AUTH_PASS}"
fi

# --- Memory path ---
if [ -n "$MEMORY_PROJECT_DIR" ]; then
  MEMORY_BASE="$HOME/.claude/projects/${MEMORY_PROJECT_DIR}/memory"
  PROJECT_DIR="$HOME/.claude/projects/${MEMORY_PROJECT_DIR}"
else
  if [ -d "$HOME/.claude/projects" ]; then
    _first_proj=$(find "$HOME/.claude/projects" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | head -1 || true)
  else
    _first_proj=""
  fi
  MEMORY_BASE="$HOME/.claude/projects/${_first_proj}/memory"
  PROJECT_DIR="$HOME/.claude/projects/${_first_proj}"
fi

# --- Genotype paths ---
BLOG_DIR="$EDGE_REPO_DIR/blog"
TOOLS_DIR="$EDGE_REPO_DIR/tools"
SECRETS_DIR="$EDGE_REPO_DIR/secrets"
CONFIG_DIR="$EDGE_REPO_DIR/config"
SEARCH_DIR="$EDGE_REPO_DIR/search"
AUTONOMY_DIR="$EDGE_REPO_DIR/autonomy"
ROUTERS_CONFIG_FILE="$CONFIG_DIR/runtime-routers.yaml"
CAPABILITIES_CONFIG_FILE="$CONFIG_DIR/capabilities.yaml"
PREFLIGHT_PROTOCOL_FILE="$CONFIG_DIR/preflight.yaml"
POSTFLIGHT_PROTOCOL_FILE="$CONFIG_DIR/postflight.yaml"

# --- Phenotype paths ---
BLOG_STATE_DIR="$EDGE_STATE_DIR/blog"
ENTRIES_DIR="$BLOG_STATE_DIR/entries"
BLOG_DIFFS_DIR="$BLOG_STATE_DIR/diffs"
COMMENTS_FILE="$BLOG_STATE_DIR/comments.json"
BLOG_CHANGELOG_FILE="$BLOG_STATE_DIR/changelog.md"
REPORTS_DIR="$EDGE_STATE_DIR/reports"
NOTES_DIR="$EDGE_STATE_DIR/notes"
BUILDS_DIR="$EDGE_STATE_DIR/builds"
LOGS_DIR="$EDGE_STATE_DIR/logs"
THREADS_DIR="$EDGE_STATE_DIR/threads"
TOPICS_DIR="$EDGE_STATE_DIR/topics"
HEALTH_DIR="$EDGE_STATE_DIR/health"
META_DIR="$EDGE_STATE_DIR/meta-reports"
SNAPSHOT_DIR="$EDGE_STATE_DIR/state-snapshots"
SCRATCHPADS_DIR="$EDGE_STATE_DIR/scratchpads"
STATE_DIR="$EDGE_STATE_DIR/state"
STATE_EVENTS_DIR="$STATE_DIR/events"
PROJECTIONS_DIR="$STATE_DIR/projections"
RUNTIME_PROTOCOL_DIR="$STATE_DIR/runtime"
SIGNALS_DIR="$STATE_DIR/signals"
EXPLORATIONS_DIR="$STATE_DIR/explorations"
SEARCH_STATE_DIR="$EDGE_STATE_DIR/search"
DB_DIR="$EDGE_STATE_DIR/db"
LIBEXEC_DIR="$EDGE_STATE_DIR/libexec/${EDGE_INSTANCE:-agent}"
SEARCH_DB_FILE="$SEARCH_STATE_DIR/edge-memory.db"
BLOG_FTS_DB_FILE="$BLOG_STATE_DIR/blog_fts.db"
BRIEFING_FILE="$EDGE_STATE_DIR/briefing.md"
EVENTS_FILE="$LOGS_DIR/events.jsonl"
CURRENT_BEAT_FILE="$STATE_DIR/current-beat.json"
CURRENT_DISPATCH_FILE="$STATE_DIR/current-dispatch.json"
TASKS_SNAPSHOT_FILE="$STATE_DIR/tasks.snapshot.json"
GIT_SIGNALS_FILE="$STATE_DIR/git-signals.json"
CURADORIA_CANDIDATES_FILE="$STATE_DIR/curadoria-candidates.json"
CURATION_DIGEST_FILE="$STATE_DIR/curation-digest.json"
PROPOSALS_FILE="$STATE_DIR/proposals.json"
PROCEDURE_CURATION_FILE="$STATE_DIR/procedure-curation.json"
WORKFLOW_HEALTH_FILE="$STATE_DIR/workflow-health.json"
FIRST_STEPS_FILE="$STATE_DIR/first-steps.json"
DISPATCH_QUEUE_FILE="$STATE_DIR/dispatch-queue.json"
HEARTBEAT_ROTATION_FILE="$STATE_DIR/heartbeat-rotation.json"
SOURCE_USAGE_FILE="$STATE_DIR/source-usage.jsonl"
SOURCES_MANIFEST_FILE="$STATE_DIR/sources-manifest.yaml"
PRIMITIVES_STATUS_FILE="$STATE_DIR/primitives-status.json"
CAPABILITIES_STATUS_FILE="$STATE_DIR/capabilities-status.json"
RENDER_INSTALL_DRIFT_FILE="$STATE_DIR/render-install-drift.json"
CLAIMS_DIGEST_FILE="$PROJECTIONS_DIR/claims-digest.json"
ORPHAN_CLAIMS_FILE="$PROJECTIONS_DIR/orphan-claims.json"
CLAIMS_VALIDATION_FILE="$PROJECTIONS_DIR/claims-validation.json"
CONTINUITY_DELTAS_DIR="$PROJECTIONS_DIR/continuity-deltas"
PREFLIGHT_COMPILED_FILE="$RUNTIME_PROTOCOL_DIR/preflight.compiled.json"
POSTFLIGHT_COMPILED_FILE="$RUNTIME_PROTOCOL_DIR/postflight.compiled.json"
PREFLIGHT_LOG_FILE="$LOGS_DIR/preflight.log"
OPS_HOTSPOTS="$STATE_DIR/ops-hotspots.json"
EXECUTION_LEDGER_FILE="$LOGS_DIR/execution-ledger.jsonl"
PIPELINE_FAILURES_FILE="$LOGS_DIR/pipeline-failures.jsonl"
SKILL_STEPS_FILE="$LOGS_DIR/skill-steps.jsonl"
STATE_LINT_FILE="$LOGS_DIR/state-lint.jsonl"
YAML_RENDER_FILE="$LOGS_DIR/yaml-render.jsonl"
HEALTH_CURRENT_FILE="$HEALTH_DIR/current.json"
HEALTH_HISTORY_FILE="$HEALTH_DIR/history.jsonl"
HEALTH_LAST_SUCCESS_FILE="$HEALTH_DIR/last_success"
AUTONOMY_CAPABILITIES_FILE="$AUTONOMY_DIR/capabilities.md"
AUTONOMY_FRONTIER_FILE="$AUTONOMY_DIR/frontier.md"

# Export key variables for shell + embedded Python heredocs
export \
  EDGE_REPO_DIR EDGE_DIR EDGE_STATE_DIR EDGE_HOME EDGE_INSTANCE MEMORY_BASE MEMORY_PROJECT_DIR PROJECT_DIR \
  BLOG_URL BLOG_AUTH_USER BLOG_AUTH_PASS BLOG_AUTH_ENABLED BLOG_PORT SKILL_PREFIX CURL_AUTH \
  BLOG_DIR TOOLS_DIR SECRETS_DIR CONFIG_DIR SEARCH_DIR AUTONOMY_DIR ROUTERS_CONFIG_FILE \
  BLOG_STATE_DIR ENTRIES_DIR BLOG_DIFFS_DIR COMMENTS_FILE BLOG_CHANGELOG_FILE REPORTS_DIR NOTES_DIR LOGS_DIR THREADS_DIR TOPICS_DIR \
  BUILDS_DIR HEALTH_DIR META_DIR SNAPSHOT_DIR SCRATCHPADS_DIR STATE_DIR STATE_EVENTS_DIR PROJECTIONS_DIR SIGNALS_DIR EXPLORATIONS_DIR \
  RUNTIME_PROTOCOL_DIR \
  SEARCH_STATE_DIR DB_DIR SEARCH_DB_FILE BLOG_FTS_DB_FILE BRIEFING_FILE EVENTS_FILE GIT_SIGNALS_FILE \
  CURRENT_BEAT_FILE CURRENT_DISPATCH_FILE TASKS_SNAPSHOT_FILE CURADORIA_CANDIDATES_FILE CURATION_DIGEST_FILE PROPOSALS_FILE PROCEDURE_CURATION_FILE WORKFLOW_HEALTH_FILE FIRST_STEPS_FILE DISPATCH_QUEUE_FILE HEARTBEAT_ROTATION_FILE SOURCE_USAGE_FILE SOURCES_MANIFEST_FILE PRIMITIVES_STATUS_FILE CAPABILITIES_STATUS_FILE RENDER_INSTALL_DRIFT_FILE CLAIMS_DIGEST_FILE ORPHAN_CLAIMS_FILE CLAIMS_VALIDATION_FILE CONTINUITY_DELTAS_DIR PREFLIGHT_LOG_FILE OPS_HOTSPOTS \
  PREFLIGHT_PROTOCOL_FILE POSTFLIGHT_PROTOCOL_FILE PREFLIGHT_COMPILED_FILE POSTFLIGHT_COMPILED_FILE \
  EXECUTION_LEDGER_FILE PIPELINE_FAILURES_FILE SKILL_STEPS_FILE STATE_LINT_FILE YAML_RENDER_FILE \
  HEALTH_CURRENT_FILE HEALTH_HISTORY_FILE HEALTH_LAST_SUCCESS_FILE AUTONOMY_CAPABILITIES_FILE LIBEXEC_DIR \
  AUTONOMY_FRONTIER_FILE
