"""Continuum init — interactive bootstrap for a new project."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import click

from continuum.config import CONTINUUM_DIR, Config, ProjectConfig, SkillsConfig, save_config


# All directories to create under .continuum/
DIRS = [
    "config",
    "memory/bootstrap",
    "memory/working",
    "memory/consolidated",
    "skills/core",
    "skills/local",
    "reports",
    "runtime/runs",
    "runtime/logs",
    "runtime/state",
    "templates",
]

# Empty working memory files
WORKING_MEMORY_FILES = [
    "memory/working/debugging.md",
    "memory/working/preferences.md",
    "memory/working/profile.md",
]

CLAUDE_MD_TEMPLATE = """\
# {project_name}

> Generated by Edge of Chaos — local-first runtime for Claude Code.

## Identity

- **Project:** {project_name}
- **Domain:** {domain}
- **Language:** {language}

## Memory

Edge of Chaos manages memory in `.continuum/memory/`:

| Layer | Path | Purpose |
|-------|------|---------|
| Bootstrap | `.continuum/memory/bootstrap/` | Extracted from transcript scan (read-only after creation) |
| Working | `.continuum/memory/working/` | Active session insights — write here freely |
| Consolidated | `.continuum/memory/consolidated/` | Periodically merged from working memory |

### Reading memory

At the start of each session, read:
1. `.continuum/memory/consolidated/` for long-term context
2. `.continuum/memory/working/` for recent notes
3. `.continuum/memory/bootstrap/` for user profile and preferences

### Writing memory

- Write insights, corrections, and discoveries to `.continuum/memory/working/`
- **Never overwrite** files in `consolidated/` — that layer is managed by the `consolidate-state` skill
- Use markdown format with clear headings

## Skills

Skills live in `.continuum/skills/` and are invoked via `continuum run <skill-id>`.

- **Core skills** (`.continuum/skills/core/`): built-in, maintained by Edge of Chaos
- **Local skills** (`.continuum/skills/local/`): project-specific, created by you

Each skill is a directory containing `skill.yaml` (manifest) and `prompt.md` (instructions).

Skill prefix: `{skill_prefix}`

Create new skills: `continuum skills new <name>`

## Conventions

- Config: `.continuum/config/continuum.toml`
- All memory files are markdown (`.md`) or JSON (`.json`)
- Skill manifests are YAML, prompts are markdown
- File names use kebab-case
- Keep working memory concise — consolidate regularly

## Preferences

{preferences_section}
"""


def _detect_github_user() -> str:
    """Try to detect GitHub username from gh CLI or git config."""
    # Try gh auth status first
    try:
        result = subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        # Parse output for account name
        for line in (result.stdout + result.stderr).splitlines():
            if "Logged in to" in line and "account" in line:
                # Format: "Logged in to github.com account <user>"
                parts = line.strip().split()
                idx = parts.index("account") if "account" in parts else -1
                if idx >= 0 and idx + 1 < len(parts):
                    return parts[idx + 1].strip("()")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    # Fallback to git config
    try:
        result = subprocess.run(
            ["git", "config", "user.name"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        name = result.stdout.strip()
        if name:
            return name
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return ""


def _create_dirs(root: Path) -> list[str]:
    """Create .continuum directory structure. Returns list of created dirs."""
    created = []
    for d in DIRS:
        path = root / CONTINUUM_DIR / d
        path.mkdir(parents=True, exist_ok=True)
        created.append(str(path.relative_to(root)))
    return created


def _create_working_memory(root: Path) -> list[str]:
    """Create empty working memory files. Returns list of created files."""
    created = []
    for f in WORKING_MEMORY_FILES:
        path = root / CONTINUUM_DIR / f
        if not path.exists():
            path.write_text("", encoding="utf-8")
            created.append(str(path.relative_to(root)))
    return created


def _generate_claude_md(cfg: Config, root: Path) -> Path:
    """Generate CLAUDE.md template from config. Returns path written."""
    content = CLAUDE_MD_TEMPLATE.format(
        project_name=cfg.project.name,
        domain=cfg.project.domain or "general",
        language=cfg.project.language,
        skill_prefix=cfg.skills.prefix,
        preferences_section="*Run `continuum scan` to populate preferences from your Claude Code transcripts.*",
    )
    path = root / CONTINUUM_DIR / "templates" / "CLAUDE.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def _install_builtin_skills(root: Path) -> list[str]:
    """Copy built-in skills to .continuum/skills/core/. Returns list of installed skill ids."""
    builtin_dir = Path(__file__).parent / "builtin_skills"
    target_dir = root / CONTINUUM_DIR / "skills" / "core"
    target_dir.mkdir(parents=True, exist_ok=True)

    installed = []
    if not builtin_dir.is_dir():
        return installed

    for skill_dir in sorted(builtin_dir.iterdir()):
        # Skip __pycache__, __init__.py, and non-directories
        if not skill_dir.is_dir() or skill_dir.name.startswith("__"):
            continue

        dest = target_dir / skill_dir.name
        # Copy the entire skill directory, overwriting if it exists
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(skill_dir, dest)
        installed.append(skill_dir.name)

    return installed


def run_init(root: Path | None = None) -> None:
    """Run the interactive init flow."""
    if root is None:
        root = Path.cwd()

    continuum_path = root / CONTINUUM_DIR

    # Check if already initialized
    if continuum_path.exists():
        click.echo(f"Warning: {CONTINUUM_DIR}/ already exists in {root}")
        if not click.confirm("Overwrite existing configuration?", default=False):
            click.echo("Aborted.")
            return

    click.echo("Welcome to Edge of Chaos! Let's set up your project.\n")

    # Interactive prompts
    default_name = root.name
    project_name = click.prompt("Project name", default=default_name)
    domain = click.prompt("Work domain (e.g. marketing, research, engineering)", default="")
    language = click.prompt("Language", default="en")
    skill_prefix = click.prompt("Skill prefix", default="cx")

    # Detect GitHub account
    gh_user = _detect_github_user()
    if gh_user:
        click.echo(f"Detected GitHub account: {gh_user}")

    # Build config
    cfg = Config(
        project=ProjectConfig(name=project_name, domain=domain, language=language),
        skills=SkillsConfig(prefix=skill_prefix),
    )

    # Create directory structure
    click.echo(f"\nCreating {CONTINUUM_DIR}/ structure...")
    created_dirs = _create_dirs(root)

    # Write config
    config_path = save_config(cfg, root)
    click.echo(f"  Created {config_path.relative_to(root)}")

    # Create working memory files
    created_files = _create_working_memory(root)
    for f in created_files:
        click.echo(f"  Created {f}")

    # Generate CLAUDE.md template
    claude_md_path = _generate_claude_md(cfg, root)
    click.echo(f"  Created {claude_md_path.relative_to(root)}")

    # Install built-in skills
    installed_skills = _install_builtin_skills(root)
    for skill_id in installed_skills:
        click.echo(f"  Installed skill: {skill_id}")

    # Summary
    click.echo(f"\n✓ Edge of Chaos initialized for '{project_name}'")
    click.echo(f"  {len(created_dirs)} directories created")
    click.echo(f"  {len(installed_skills)} built-in skills installed")
    click.echo(f"  Config: {config_path.relative_to(root)}")
    click.echo(f"  CLAUDE.md template: {claude_md_path.relative_to(root)}")

    if gh_user:
        click.echo(f"  GitHub user: {gh_user}")

    click.echo("\nNext steps:")
    click.echo("  1. Run `continuum scan` to analyze your Claude Code transcripts")
    click.echo(f"  2. Copy {claude_md_path.relative_to(root)} to your project root or ~/.claude/")
    click.echo("  3. Run `continuum doctor` to verify setup")
