"""briefing — the deterministic composer of Memento's tattoo (ADR-0009). Genotype tool.

The agent has anterograde amnesia: it must orient **entirely** from the briefing and trust
nothing that isn't inscribed there (CONTEXT.md, the `**Briefing**` entry). So the load-bearing
lines — the curated Direction, what is open / the next bet, the source yield, what the agent
already did — are **deterministically inscribed from the log** (folds of `tools/eventlog.py`),
never left to an LLM to remember. Only the **Recap** (the corpus↔live-Atividade relation) is
synthesized fresh; `assemble` fills its slot. Tier-0 composes from the log alone — the graph
(Knowledge clusters) degrades where there is no runtime, never crashes.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from eventlog import (LOG, direction_at, corpus_at, artefatos_without_kernel,  # noqa: E402
                      source_yield_at)

KIND_ORDER = ["phase", "priority", "constraint", "thread"]


def _render_direction_items(items):
    by_kind = {}
    for it in items:
        by_kind.setdefault(it.get("kind", "thread"), []).append(it)
    lines = []
    for kind in KIND_ORDER + [k for k in by_kind if k not in KIND_ORDER]:
        for it in by_kind.get(kind, []):
            lines.append(f"- **[{kind}]** {it.get('body', '')}")
    return "\n".join(lines) if lines else "_none_"


def _section_direction(log, seq, ts):
    d = direction_at(seq=seq, ts=ts, log=log)
    if d is None:
        return "## 1. Direction\n\n_no direction set yet._"
    return ("## 1. Direction\n\n"
            "**Set — curated (Voz, highest authority):**\n\n"
            f"{_render_direction_items(d.get('set', []))}\n\n"
            "**Proposed — non-curated (grill achados):**\n\n"
            f"{_render_direction_items(d.get('proposed', []))}")


def _section_continuity(corpus):
    """The literal tattoo: what the cold agent was mid-doing — the *why* of the most-recent
    kernels, most-recent-first. Empty corpus (or no recorded why yet) → an honest empty marker."""
    whys = [c["intent"] for c in reversed(corpus) if c.get("intent")]
    body = "\n".join(f"- {w}" for w in whys[:2]) if whys else "_nothing open recorded yet._"
    return f"## 2. What is open / the next bet\n\n{body}"


def _section_corpus(corpus, debt):
    """What I already did: recent slugs + their why, most-recent-first, so the agent builds rather
    than repeats. Kernel-less Artefatos are surfaced as C3 debt (show the gap, don't hide it)."""
    if not corpus:
        body = "_no corpus yet._"
    else:
        lines = []
        for it in reversed(corpus):
            why = it.get("intent") or "_no intent recorded (C3 debt)_"
            lines.append(f"- **{it['slug']}** — {why}")
        body = "\n".join(lines)
    if debt:
        body += "\n\n**C3 debt** (Artefatos with no recorded intent): " + ", ".join(debt)
    return f"## 3. Corpus — what I already did\n\n{body}"


def _section_sources(log, seq, ts):
    """Per-source yield (ref · kind · count · mean sim), highest yield first — the leg the grill
    consults. Empty → "no source signals yet" (degrade, never crash)."""
    yld = source_yield_at(seq=seq, ts=ts, log=log)
    if not yld:
        return "## 4. Source orientation\n\n_no source signals yet._"
    rows = sorted(yld.values(), key=lambda r: r["mean_similarity"], reverse=True)
    lines = [f"- **{r['ref']}** ({r['kind']}) · {r['count']}× · mean sim {r['mean_similarity']:.2f}"
             for r in rows]
    return "## 4. Source orientation\n\n" + "\n".join(lines)


def _section_clusters(clusters):
    """Knowledge clusters (← graph, Tier-1). None → the Tier-0 degrade note (no graph runtime;
    knowledge = the swept log + Direction). Never crash on the missing graph."""
    if clusters is None:
        return ("## 5. Knowledge clusters\n\n"
                "_Tier-0: clusters unavailable — no graph runtime; "
                "knowledge = the swept log + Direction._")
    if not clusters:
        return "## 5. Knowledge clusters\n\n_none._"
    return "## 5. Knowledge clusters\n\n" + "\n".join(f"- {c}" for c in clusters)


def _section_recap(recap):
    """Recap (← corpus): the one synthesized-fresh part — the corpus↔live-Atividade relation.
    None → a slot marker the assemble LLM fills; otherwise inscribe the synthesized text."""
    body = recap or "_(Recap synthesized at compose-time — corpus × live Atividade)_"
    return f"## 6. Recap\n\n{body}"


BANNER = ("<!-- generated by tools/briefing.py — Memento's tattoo (ADR-0009); "
          "load-bearing lines inscribed from the log, only the Recap synthesized fresh -->")


def compose_briefing(log=LOG, recap=None, clusters=None, seq=None, ts=None):
    """Render the briefing (Memento's tattoo) as one markdown string, from the log. Deterministic:
    sections in tattoo priority (load-bearing first). Cursor-aware (seq/ts) like the folds it reads."""
    corpus = corpus_at(seq=seq, ts=ts, log=log)
    parts = [
        BANNER + "\n# Briefing — orient entirely from here",
        _section_direction(log, seq, ts),
        _section_continuity(corpus),
        _section_corpus(corpus, artefatos_without_kernel(log=log)),
        _section_sources(log, seq, ts),
        _section_clusters(clusters),
        _section_recap(recap),
    ]
    return "\n\n".join(parts) + "\n"
